### ISSUE TITLE
Nagstamon 3.14 not starting since Plasma 6

### ISSUE THREAD

**Issue by timodenissen** [HenriWahl/Nagstamon#1015]
Using Arch Linux with the most recent Plasma 6 update, Nagstamon 3.14 no longer starts.

Cleaning my configuration to make sure it's not a profile problem:
```bash
cd ~
mv .nagstamon{,_orig}
```

Starting Nagstamon from Konsole via `nagstamon` crashes:
```
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QThread: Destroyed while thread is still running
zsh: IOT instruction (core dumped)  nagstamon
```

Running from `bash` results in:
```
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QThread: Destroyed while thread is still running
Aborted (core dumped)
```

`ps auxf | grep -i "nagstamon"` shows no Nagstamon process is running.

Prior the Plasma 6 update (with Plasma 5.27) everything worked just fine.

**Comment by HenriWahl** [comment]
Hi @timodenissen, how bad. Actually Nagstamon supports Qt6, which Plasma 6 is based on too. So this is really strange. I will try to reproduce by setting up an Arch instance.

**Comment by HenriWahl** [comment]
Hi @timodenissen - do you know of an fast way to get an Arch Linux up and running? I did not expect to come out in a shell for installing. Don't get me wrong, I :heart: shells, but looks more tenacious than assumed.

**Comment by HenriWahl** [comment]
@timodenissen how did you install Nagstamon?

**Comment by timodenissen** [comment]
@HenriWahl The fastest way could be using [`archinstall`](https://wiki.archlinux.org/title/archinstall).

I use the Plasma wayland session, with Plasma 5.27 this was not an issue.

I installed Nagstamon via the [AUR package](https://aur.archlinux.org/packages/nagstamon). A clone of the repository also results in the same errros.

**Comment by 11qeq11** [comment]
+1 to the issue, after recent system upgrade Nagstamon won't load anymore. I also noticed that trying to run nagstamon via [pdb-clone](https://aur.archlinux.org/packages/python-pdb-clone), I can get it to work but without any UI whatsover - I hear the sound of alerts, can see the process running, but UI appears for a fraction of a second and immediately crashes. 

Not sure how helpful it will be for debugging, but will leave the outputs, in `~/.nagstamon/nagstamon.conf` I enabled debug mode:

```
...
debug_mode = True
...
```

<details><summary> Output from pdb </summary>
<p>

```console
$ ps auxf | grep -i "nagstamon"
alex     1308329  6.8  0.9 2679496 307964 pts/10 Sl+  18:51   0:01  |   |       \_ /usr/bin/python /usr/bin/pdb-clone /usr/bin/nagstamon
alex     1308997  0.0  0.0   6572  2560 pts/14   S+   18:51   0:00  |           \_ grep --color=auto -i nagstamon
alex     1308441  0.0  0.0 268530852 25836 ?     S    18:51   0:00  \_ /usr/lib/kf6/kioworker /usr/lib/qt6/plugins/kf6/kio/tags.so tags  local:/run/user/1000/nagstamonFUaGdH.1.kioworker.socket
```

```console
$ pdb-clone /usr/bin/nagstamon
pdb-clone 1.10.1 (without the _bdb extension module).
> /usr/bin/nagstamon(21)<module>()
-> import sys
(Pdb) c
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
DEBUG: 2024-03-15 18:54:51.612610 Saving configuration to file /home/alex/.nagstamon/nagstamon.conf
DEBUG: 2024-03-15 18:54:51.865950 QU Created server.
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7d2bf9b0cdc0> for state "OK"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7d2bf9b0cca0> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7d2bf9b0ce50> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7d2bf9b0cee0> for state "WARNING"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7d2bf9b0cf70> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7d2bf9b0d000> for state "HIGH"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7d2bf9b0d090> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7d2bf9b0d120> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7d2bf9b0d1b0> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7d2bf9b0d240> for state "DOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7d2bf9b0d2d0> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt6.QtGui.QIcon object at 0x7d2bf9b0cb80>
DEBUG: 2024-03-15 18:54:52.315903 QU FetchURL: https://my.nagios.server.com/nagios/cgi-bin/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=262144&limit=0 CGI Data: None
The program exited via sys.exit(). Exit status: 0
> /usr/bin/nagstamon(21)<module>()
-> import sys
(Pdb) DEBUG: 2024-03-15 18:54:52.370530 QU FetchURL: https://nagstamon.de/version/stable CGI Data: None
DEBUG: 2024-03-15 18:54:53.566737 QU FetchURL: https://my.nagios.server.com/nagios/cgi-bin/status.cgi?hostgroup=all&style=hostdetail&hoststatustypes=12&hostprops=524288&limit=0 CGI Data: None
DEBUG: 2024-03-15 18:54:54.490641 QU FetchURL: https://my.nagios.server.com/nagios/cgi-bin/status.cgi?host=all&servicestatustypes=253&serviceprops=262144&limit=0 CGI Data: None
DEBUG: 2024-03-15 18:54:55.755790 QU FetchURL: https://my.nagios.server.com/nagios/cgi-bin/status.cgi?host=all&servicestatustypes=253&serviceprops=524288&limit=0 CGI Data: None
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
DEBUG: 2024-03-15 18:54:56.628821 QU Filter: REGEXP <redacted>
DEBUG: 2024-03-15 18:54:56.628842 QU Filter: ACKNOWLEDGED <redacted>
DEBUG: 2024-03-15 18:54:56.628895 QU Filter: ACKNOWLEDGED <redacted>
...
```

</p>
</details>

**Comment by HenriWahl** [comment]
@timodenissen thanks for the hint with `archinstall`. The downside is that I only receive a black screen after logging in into Plasma desktop inside a VM.

What is your desktop session manager? I choose the default sddm (or something like that).

**Comment by timodenissen** [comment]
I use SDDM with no special configuration. Please be aware that X11 is no longer supported by Plasma 6 and may falsify reproducing the error.

**Comment by HenriWahl** [comment]
Yes, I think checking it with Wayland is definitely more useful. I will try to get it running.

**Comment by HenriWahl** [comment]
At least got Wayland session of Plasma6 running in VM. Now the next questions as non-Arch-user: where did you install Nagstamon from?

**Comment by HenriWahl** [comment]
@timodenissen the mention of `libpulse` inspired me to try to disable sound.
I started from source in virtualenv environment where it does not crash and disabled sound. 
Back with normal nagstamon start it does at least not crash now at the beginning. So I am almost convinced something with ArchLinux Qt6 + sound (libpulse?) is wrong, Maybe some package is missing and should also be listed as dependency?

**Comment by HenriWahl** [comment]
@timodenissen well, I installed the not yet installed package pulseaudio-qt and now there is no crash. Can you reproduce this?

**Comment by bouzouste** [comment]
@HenriWahl , @timodenissen I am sorry for stepping in. I personally use Endeavour OS (arch based) which also seems to have an issue with nagstamon after updating to Plasma 6. I also have the `PulseAudio-qt` package installed and I still see core dumps. However, in my case, nagstamon somehow seems to be working if it is **not** set to display a floating status bar but rather shows an icon in systray

**Comment by bouzouste** [comment]
@timodenissen I confirm that the app crashes even when there is no configuration. However, If you already have a conf file, you could try changing the following two lines:
```
statusbar_floating = False
icon_in_systray = True
``` 
so that the floating status bar is disabled, and it (probably) won't crash.

If on the other hand, you don't have any configuration available, then you could try using an older version of nagstamon (3.8.0 or older) which seems to be working without issues (versions 3.8.1+ to 3.14+ seem to not like plasma 6)

**Comment by timodenissen** [comment]
@bouzouste Thanks, now Nagstamon's not crashing but shows me a flashing tray icon (expected) but unfortunately I need the window =/ I wait for @HenriWahl to check and add a fix (not that much of a coder myself) or wait for the flatpak to update to latest stable (currently 3.6.0, which somehow can't work with our Prometheus Alert Manager).

In the meantime I check the Nagios and Prometheus Alert Manager with their respective web interfaces.

**Comment by HenriWahl** [comment]
@timodenissen strange thing that the window isn't working. Well, maybe you could test the 3.14 flatpak release currently being in development at https://github.com/flathub/de.ifw_dresden.nagstamon/pull/8

**Comment by HenriWahl** [comment]
https://flathub.org/apps/de.nagstamon.nagstamon is finally out.

**Comment by gaestur** [comment]
Fedora 40, Plasma 6. Neither 3.14 from flathub (de.nagstamon.nagstamon), nor 3.14 (or 3.15 from the "latest" repo) RPMs work.
Here's an output (it is +/- similar in all cases)
`$ flatpak run de.nagstamon.nagstamon
Qt: Session management error: Could not open network socket
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
qt.multimedia.ffmpeg.libsymbolsresolver: Couldn't load VAAPI library
QThread: Destroyed while thread is still running
`

This is after manually permitting flatpak access to system and session buses. Without it (by default) it additionally gives multiple errors like this:
`kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"`

**Comment by timodenissen** [comment]
Even after updating to Python 3.12, Nagstamon 3.14 won't show the GUI, neither does using the flatpak `de.ifw_dresden.nagstamon`.

**Comment by HenriWahl** [comment]
@timodenissen please try the new flatpak de.nagstamon.nagstamon

**Comment by richarson** [comment]
@HenriWahl same behaviour for me with the latest flatpak as with running from the tar.gz, the UI flashes and immediately closes.

```
$ flatpak run de.nagstamon.nagstamon
Qt: Session management error: Could not open network socket
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected"
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected"
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected"
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected"
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected"
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected"
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected"
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected"
 "Not connected to D-Bus server"
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
qt.multimedia.ffmpeg.libsymbolsresolver: Couldn't load VAAPI library
=2
```

**Comment by bbhtt** [comment]
> @bbhtt do you think the permissions should be increased?

It does not need system or session bus. You need to figure out which bus name it tries to connect to by running it with `flatpak run --log-session-bus <appid>` and dbus-monitor etc.

**Comment by timodenissen** [comment]
I did a quick test with the latest main branch:
```bash
cd /tmp
git clone https://github.com/HenriWahl/Nagstamon.git
cd Nagstamon
python ./setup.py build
python ./build/scripts-3.12/nagstamon.py
```

results in

```
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
```

Same error - the status window doesn't open.

When stopping `Nagstamon.py` from the systray via the context menu quits the process, using Ctrl+C results in:

```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/Nagstamon/QUI/__init__.py", line 2553, in reset
    @Slot()

KeyboardInterrupt
zsh: IOT instruction (core dumped)  python ./build/scripts-3.12/nagstamon.py
```

Running the latest flatpak `de.nagstamon.nagstamon` still doesn't work.

**Comment by HenriWahl** [comment]
At least I can confirm that the flatpak does not run on a fresh Fedora 40 Plasma install.

I tried to run it from source on Fedora 40 Plasma and there it runs with Python 3.12.3 and Qt 6.7.0. Qt6 is missing some multimedia backend:

![grafik](https://github.com/HenriWahl/Nagstamon/assets/2835065/6c1c5f78-b0c2-4f9a-86ca-2fd37c841a54)

Maybe this leads to a solution, I will check later.

**Comment by timodenissen** [comment]
With some recent QT updates, I now get these new messages:
```
qt.core.qobject.connect: QObject::connect: No such signal Solid::Backends::Fstab::FstabStorageAccess::repairRequested(QString)
qt.core.qobject.connect: QObject::connect: No such signal Solid::Backends::Fstab::FstabStorageAccess::repairDone(Solid::ErrorType, QVariant, QString)
qt.core.qobject.connect: QObject::connect: No such signal Solid::Backends::Fstab::FstabStorageAccess::repairRequested(QString)
qt.core.qobject.connect: QObject::connect: No such signal Solid::Backends::Fstab::FstabStorageAccess::repairDone(Solid::ErrorType, QVariant, QString)
```

**Comment by HenriWahl** [comment]
Does it run? And in which context did you get this updates? On your Linux system or in virtualenv?

**Comment by timodenissen** [comment]
> Does it run? And in which context did you get this updates? On your Linux system or in virtualenv?

Regular updates on my productive laptop with Arch Linux. The flatpak still doesn't work and still won't show a GUI as well.

The following QT packages are installed:
```
python-pyqt5 5.15.10-2
python-pyqt5-sip 12.13.0-2
python-pyqt6 6.7.0-2
python-pyqt6-sip 13.6.0-2
python-qtpy 2.4.1-3
qt5-base 5.15.13+kde+r145-1
qt5-charts 5.15.13-1
qt5-declarative 5.15.13+kde+r30-1
qt5-feedback 0.0.0.20150918-4
qt5-graphicaleffects 5.15.13-1
qt5-imageformats 5.15.13+kde+r7-1
qt5-location 5.15.13+kde+r6-1
qt5-multimedia 5.15.13+kde+r2-1
qt5-networkauth 5.15.13-1
qt5-quickcontrols 5.15.13-1
qt5-quickcontrols2 5.15.13+kde+r5-1
qt5-script 5.15.16-4
qt5-sensors 5.15.13-1
qt5-speech 5.15.13+kde+r1-1
qt5-svg 5.15.13+kde+r6-1
qt5-tools 5.15.13+kde+r4-1
qt5-translations 5.15.13-1
qt5-wayland 5.15.13+kde+r60-1
qt5-webchannel 5.15.13+kde+r3-1
qt5-webengine 5.15.16-6
qt5-websockets 5.15.13+kde+r2-1
qt5-webview 5.15.13-1
qt5-x11extras 5.15.13-1
qt5-xmlpatterns 5.15.13-1
qt6-5compat 6.7.0-1
qt6-base 6.7.0-6
qt6-charts 6.7.0-1
qt6-declarative 6.7.0-1
qt6-httpserver 6.7.0-1
qt6-imageformats 6.7.0-1
qt6-location 6.7.0-1
qt6-multimedia 6.7.0-1
qt6-multimedia-ffmpeg 6.7.0-1
qt6-networkauth 6.7.0-1
qt6-positioning 6.7.0-2
qt6-quick3d 6.7.0-1
qt6-quicktimeline 6.7.0-1
qt6-scxml 6.7.0-1
qt6-sensors 6.7.0-1
qt6-shadertools 6.7.0-1
qt6-speech 6.7.0-1
qt6-svg 6.7.0-1
qt6-tools 6.7.0-2
qt6-translations 6.7.0-1
qt6-virtualkeyboard 6.7.0-1
qt6-wayland 6.7.0-1
qt6-webchannel 6.7.0-1
qt6-webengine 6.7.0-1
qt6-websockets 6.7.0-1
qt6-webview 6.7.0-1
qtkeychain-qt5 0.14.3-1
qtkeychain-qt6 0.14.3-1
```

**Comment by timodenissen** [comment]
Okay now this is strange... I have no new Arch updates installed since yesterday and wanted to dive deepter into debugging. I installed Nagstamon via flatpak in an Ubuntu 24.04 VM and it worked, went back to Arch and... now it's working.

After cloning this repository to `/tmp` and starting `nagstamon.py` from the just very checked out repository I was presented with the "Create new configuration" dialog window. My configuration is gone but at least I can work with Nagstamon again.

Running Nagstamon via the [AUR package](https://aur.archlinux.org/packages/nagstamon) works as intended again.

For me this issue is resolved.

**Comment by richarson** [comment]
I still can't run nagstamon, either from flatpak or from git, under X11 or Wayland.

Under Wayland from git I get additional errors, maybe due to Fedora's python version (3.12.3)?:
```
$ ./nagstamon.py
/home/richis/bin/Nagstamon/Nagstamon/thirdparty/zabbix_api.py:293: SyntaxWarning: invalid escape sequence '\s'
  if re.search(".*already\sexists.*", jobj["error"]["data"], re.I):  # already exists
/home/richis/bin/Nagstamon/Nagstamon/Servers/Livestatus.py:71: SyntaxWarning: invalid escape sequence '\d'
  m = re.match('.*?://([^:/]+?)(?::(\d+))?(?:/|$)', self.monitor_url)
/home/richis/bin/Nagstamon/Nagstamon/Servers/Monitos3.py:90: SyntaxWarning: invalid escape sequence '\d'
  m = re.match('.*?://([^:/]+?)(?::(\d+))?(?:/|$)', self.monitor_url)
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
qt.multimedia.ffmpeg.libsymbolsresolver: Couldn't load VAAPI library
=2
```

**Comment by richarson** [comment]
OK, those additional errors are fixed/silenced with this Arch fix:

```
sed -i Nagstamon/QUI/qt.py -e "s/QT_VERSION_STR.split('.')/QT_VERSION_STR.split('.')[0:3]/"
```

Still, nagstamon is not working for me :(

**Comment by skreech1** [comment]
This is happening on Manjaro 24.0.1 as well. Attempting start on a clean config results in a core dump. The flatpak version acts the same. I've also forced rebuilds of both nagstamon and nagstamon-git AUR packages. Below, I used the following config:

```
[Nagstamon]
debug_mode = True
debug_to_file = False
```

```
qt.core.qobject.connect: QObject::connect: No such signal Solid::Backends::Fstab::FstabStorageAccess::repairRequested(QString)
qt.core.qobject.connect: QObject::connect: No such signal Solid::Backends::Fstab::FstabStorageAccess::repairDone(Solid::ErrorType, QVariant, QString)
qt.core.qobject.connect: QObject::connect: No such signal Solid::Backends::Fstab::FstabStorageAccess::repairRequested(QString)
qt.core.qobject.connect: QObject::connect: No such signal Solid::Backends::Fstab::FstabStorageAccess::repairDone(Solid::ErrorType, QVariant, QString)
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7c35d9cfc7d0> for state "OK"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7c35d9cfc550> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7c35d9cfc910> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7c35d9cfc9b0> for state "WARNING"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7c35d9cfcaf0> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7c35d9cfcc30> for state "HIGH"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7c35d9cfcd70> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7c35d9cfceb0> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7c35d9cfcff0> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7c35d9cfd130> for state "DOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7c35d9cfd1d0> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt6.QtGui.QIcon object at 0x7c35d9cfd450>
QThread: Destroyed while thread is still running
Aborted (core dumped)
```

Version parsing is not a problem in this case. Some GUI elements make a blink appearance before the core dump. Under a default config I can tell the main window and the "There are no servers configured yet" dialog both appear, but this took many repetitions to observe as these elements are only visible for one frame.

trace: [info.txt](https://github.com/user-attachments/files/15744688/info.txt)

**Comment by skreech1** [comment]
After an incremental system upgrade and forced rebuild of the nagstamon package, this seems to be resolved in Manjaro. I think the package rebuild wasn't necessary. Several qt5 packages were upgraded from 5.15.13 to 5.15.14, and I suspect these were the key.
