### ISSUE TITLE
v2.0 Feature Request: wrong password not poll after 5 queries

### ISSUE THREAD

**Issue by terratectom** [HenriWahl/Nagstamon#190]
I have tested the version 2.0 ALPHA 20160206. The biggest problems at login handling from the 1.x version are fixed.

Feature Request:
- Not only show that a wrong password is used, but also after 5-10 queries the poll quit until a new password is stored.
- Display if no profile is active.

**Comment by HenriWahl** [comment]
Sounds interesting.

**Comment by terratectom** [comment]
Thanks for the new version 2.0. We use this active on Win7 and Win10 PCs. We are pleased that many problems with the 1.x are fixed.

Only alone remains is the desire with the Password. Is there already a plan how it goes with version 2.x?

**Comment by HenriWahl** [comment]
Not yet but still on the todo list.

**Comment by terratectom** [comment]
It is nice that it continues in the development and the new version 3.x offers many improvements. A pity is only that this request is not yet implemented.

Is it foreseeable that this option is still being implemented?

**Comment by HenriWahl** [comment]
Sorry for the late answer - there had been vacations in between. And after vacations all the stuff not being done during vacations...
This issue still is not forgotten but as there where (and are) some more critical bugs after the last stable release they have higher priority.

**Comment by glipscomb** [comment]
Is this still work in progress?
We have just enabled password lockout and if the password in nagstamon is not updated soon after the user changes their password they get locked out of ALL systems.

**Comment by glipscomb** [comment]
Is this still work in progress?
If the password in nagstamon is not updated soon after the user changes their password they get locked out of ALL systems.

**Comment by HenriWahl** [comment]
Well, it has been quite a while.... now we are looking into this. If you are still using Nagstamon or a monitoring server - can you please tell me which monitoring Server do you use? The problem is that such a feature needs to be adjusted for every single monitoring server type.
